import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from '@/app/context/Authcontext'
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { redirect } from 'next/navigation';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
 

   
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider>
       {children}
      </SessionProvider>
      </body>
    </html>
  );
}
